let questions = [
  new Question("XXXXXXXXXXXXX", ["AAAAAAAAAA", "BBBBBBBBBB", "CCCCCCCCCC", "DDDDDDDDDD"], "C"),
  new Question("XXXXXXXXXXXXX", ["AAAAAAAAAA", "BBBBBBBBBB", "CCCCCCCCCC", "DDDDDDDDDD"], "C"),
  new Question("XXXXXXXXXXXXX", ["AAAAAAAAAA", "BBBBBBBBBB", "CCCCCCCCCC", "DDDDDDDDDD"], "C"),
  new Question("XXXXXXXXXXXXX", ["AAAAAAAAAA", "BBBBBBBBBB", "CCCCCCCCCC", "DDDDDDDDDD"], "C"),
  new Question("XXXXXXXXXXXXX", ["AAAAAAAAAA", "BBBBBBBBBB", "CCCCCCCCCC", "DDDDDDDDDD"], "C"),
];